name: Publish Packages

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@aknorw"

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      # Because of the prepublishOnly script, packages will be built before being published.
      - name: Publish packages
        run: yarn publish-ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}} # Must need to edit this?
