name: Release

on:
  push:
    branches:
      - develop

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # If no changesets were found, it won't open a PR nor throw an error.
      - name: Create Release Pull Request
        uses: changesets/action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # Automatically created by GitHub.

  publish:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == 'true'
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@aknorw"

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      # Because of the prepublishOnly script, packages will be built before being published.
      - name: Publish packages
        run: yarn publish-ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
